"""create books table

Revision ID: e1f5f2f27932
Revises: 33793e46cba9
Create Date: 2025-01-29 00:16:36.493330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1f5f2f27932"
down_revision: Union[str, None] = "33793e46cba9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_name", sa.String(length=30), nullable=False),
        sa.Column("author", sa.String(length=30), nullable=False),
        sa.Column("genre", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###
